export const getQAList=[
  {
    issue:'工具有介绍如何使用吗？',
    answer:'请点链接观看说明影片',
    type:'video',
    url:'https://source.vipabc.com/ext/media/CPS/guide.mp4'
  },
  {
    issue:'这个CPS的返佣是多少？',
    answer:'100%全部返佣哦！比如你卖了一个399元的产品，399元都归你。',
    type:'text',
    url:''
  },
  {
    issue:'产品售出后，奖金多久结算一次？',
    answer:'只要客户过了退费期，你就可以领全额奖金，我们是周结算，每周四打款，请安心。[客户一览]页面有您的销售记录，您都可以随时查看。',
    type:'text',
    url:''
  },
  {
    issue:'结算款项打到银行卡还是支付宝？',
    answer:'银行卡',
    type:'text',
    url:''
  },
  {
    issue:'客户如何购买？',
    answer:'点击产品列表里面直接分享二维码，客户就可以透过你的专属二维码扫码购买。',
    type:'text',
    url:''
  },
  {
    issue:'可以让好友帮忙转发我的二维码吗？',
    answer:'可以的，只要任何人透过你发出去的文章或图片扫码，销售业绩100%都算你的，直接计入你的账号。',
    type:'text',
    url:''
  },
  {
    issue:'会给客户安排demo吗？',
    answer:'是的，我们将会安排demo，帮助学员开课，一如既往真心服务。',
    type:'text',
    url:''
  },
  {
    issue:'demo程度分级是多久安排呢？',
    answer:'理论上是一天内，如果有任何问题，请在这里找我们，我們会立即处理。',
    type:'text',
    url:''
  },
  {
    issue:'我想看下CPS代销协议',
    answer:'协议都是电子版，您注册后登入点击产品列表就可以看到了喔，视频教程里有喔。',
    type:'text',
    url:''
  },
  {
    issue:'如果个人资料信息有误怎么办？',
    answer:'因为我们现阶段是邀请制，所以暂时需要联系我们更改，有任何问题都请找我们喔。',
    type:'text',
    url:''
  },
  {
    issue:'可以推给朋友做代销么？',
    answer:'抱歉，目前我们是内部邀请制，所以只有开放1000个名额。',
    type:'text',
    url:''
  },
];